/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppArchivosRouteImport } from './routes/_app.archivos'
import { Route as AppAsistenteRouteImport } from './routes/_app.asistente'
import { Route as AppChatsRouteImport } from './routes/_app.chats'
import { Route as AppConexionesRouteImport } from './routes/_app.conexiones'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppArchivosRoute = AppArchivosRouteImport.update({
  id: '/archivos',
  path: '/archivos',
  getParentRoute: () => AppRoute,
} as any)
const AppAsistenteRoute = AppAsistenteRouteImport.update({
  id: '/asistente',
  path: '/asistente',
  getParentRoute: () => AppRoute,
} as any)
const AppChatsRoute = AppChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AppRoute,
} as any)
const AppConexionesRoute = AppConexionesRouteImport.update({
  id: '/conexiones',
  path: '/conexiones',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/archivos': typeof AppArchivosRoute
  '/asistente': typeof AppAsistenteRoute
  '/chats': typeof AppChatsRoute
  '/conexiones': typeof AppConexionesRoute
}
export interface FileRoutesByTo {
  '/archivos': typeof AppArchivosRoute
  '/asistente': typeof AppAsistenteRoute
  '/chats': typeof AppChatsRoute
  '/conexiones': typeof AppConexionesRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/archivos': typeof AppArchivosRoute
  '/_app/asistente': typeof AppAsistenteRoute
  '/_app/chats': typeof AppChatsRoute
  '/_app/conexiones': typeof AppConexionesRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/archivos' | '/asistente' | '/chats' | '/conexiones'
  fileRoutesByTo: FileRoutesByTo
  to: '/archivos' | '/asistente' | '/chats' | '/conexiones' | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/archivos'
    | '/_app/asistente'
    | '/_app/chats'
    | '/_app/conexiones'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/archivos': {
      id: '/_app/archivos'
      path: '/archivos'
      fullPath: '/archivos'
      preLoaderRoute: typeof AppArchivosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/asistente': {
      id: '/_app/asistente'
      path: '/asistente'
      fullPath: '/asistente'
      preLoaderRoute: typeof AppAsistenteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chats': {
      id: '/_app/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AppChatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/conexiones': {
      id: '/_app/conexiones'
      path: '/conexiones'
      fullPath: '/conexiones'
      preLoaderRoute: typeof AppConexionesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppArchivosRoute: typeof AppArchivosRoute
  AppAsistenteRoute: typeof AppAsistenteRoute
  AppChatsRoute: typeof AppChatsRoute
  AppConexionesRoute: typeof AppConexionesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppArchivosRoute: AppArchivosRoute,
  AppAsistenteRoute: AppAsistenteRoute,
  AppChatsRoute: AppChatsRoute,
  AppConexionesRoute: AppConexionesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
